# -*- coding: utf-8 -*-
"""Aklilu_Download_Historical_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QFGbk5xseW8WqtBzNlDrcfxUpML4w0L7

# 3b-i-1
"""

import yfinance as yf
import pandas as pd

# Download Amazon stock data from 2000 to today
ticker = "AMZN"
data = yf.download(ticker, start="2000-01-01")

# Keep only the needed columns
data = data[['Open', 'High', 'Low', 'Close', 'Volume']]

# Reset index to bring 'Date' out of the index and into a column
data.reset_index(inplace=True)

# Save the data
output_filename = "Aklilu_Historical_Data.csv"
data.to_csv(output_filename, index=False)

# Print confirmation
print(f"Saved Amazon historical stock data to: {output_filename}")